language: node_js
sudo: true
node_js:
  - "4"
  - "6"

matrix:
  allow_failures:
   - node_js: "6"

addons:
  apt:
    packages:
      - dh-make
      - devscripts
      - debhelper
      - git
      - default-jdk
      - maven

services:
 - mongodb
 - rabbitmq

after_success:
 - ./extra/make-testcoveralls.sh

before_deploy:
 - >
   if ! [ "$BEFORE_DEPLOY_RUN" ]; then
     export BEFORE_DEPLOY_RUN=1;
     ./extra/make-docs.sh;
     ./extra/make-deb.sh;
   fi

deploy:
  - provider: bintray
